#+TITLE: FedEx vs UPS: Case Notes and Questions
#+AUTHOR: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>

* Concepts to Review/Highlight:
** Financial Ratios
1.  Financial ratio values can be volatile. Don't pick out one ratio for one particular year and draw conclusions from it---it could be due to particular charges unique to that year.  Instead, look at the trend in the ratio over time and its relation over time to the same ratio at a similar firm.

2.  Know what are good values of a particular ratio.

3.  Many different ratios measure the same thing, so don't spend time analyzing each.  For example, we can see that Fedex's debt to equity ratio is declining.  Given this we would *expect* its Time-Interest-Earned ratio to increase, which it does.  So there is no need to discuss both ratios.  It is possible, though rare, that the Time-Interest-Earned ratio may not increase.  If this were the case then discussing why would be relevant.  

4.  Each financial ratio is intended to measure a particular aspect of the firm's performance.  Be sure to know what each ratio is measuring.

Question: which ration are least important?


** Net Operating Profit After Tax (NOPAT)

Measures such as NOPAT and Earnings Before Interest and Taxes (EBIT) attempt to estimate a firm's cash flow.

** Economic Value Added (EVA)

EVA is a method of measuring corporate performance that is used in many prominent firms such as AT&T , Coca-Cola, and Toyota.  The idea is to compare cash flow the firm generates to the payments the firm must make to debt and equity holders (WACC times capital).

$$RONA * Capital - WACC * Capital \approx Cash\ Flow\ Generated - Cost\ of\ Capital\ in\ Dollars$$

  Ideally these should be market values, however we often must work with accounting values.

#+begin_src C :includes <stdio.h> :exports both
int
main(){
  double NOPAT = 1448;
  double Capital = 9679; /*Capital employed in the business or operation, how does this differ from total assets?*/
  double RONA = NOPAT / Capital; //return on net assets
  double WACC = 0.1272;
  double EVA = (RONA - WACC) * Capital;
  printf("The Economic Value Added is $%.2f\n", EVA);
  return 0;
}
#+end_src

#+results:
: The Economic Value Added is $216.83

** WACC

$WACC = w_e r_e + w_d r_d (1 - \tau)$

where $w_e$ and $w_d$ is the weight of equity and debt, respectively in the capital structure.  $r_e$ and $r_d$ are the required returns on equity and debt, and $\tau$ is the tax rate.

*** Cost of Debt

We get the cost of debt by observing the yield-to-maturity on the firm's outstanding debt.  If the debt is not traded, we may have to find similar debt that is traded.  

*** Cost of Equity

We can get $r_e$ from the CAPM: $r_e = r_f + \beta_e (r_m - r_f)$  Using a python class and method to calculate the return on equity.

#+begin_src python :exports both :results output
class CAPMdata:
     """a data structure to hold capm data"""
     def __init__(self, risk_free, beta, return_market):
         self.rf = risk_free
         self.b = beta
         self.rm = return_market

     def capm(self):
         return self.rf + self.b * (self.rm - self.rf)

print("This required return on equity is {0:.2%}".format(CAPMdata(.03, 1.5, .08).capm()))
#+end_src

#+results:
: This required return on equity is 10.50%

*** Putting it together to calculate the WACC

#+begin_src C :includes <stdio.h> :exports both
double capm(double rf, double beta, double rm){
return rf + beta * (rm - rf);
}

double wacc(double wd, double we, double re, double rd, double tax){
return we * re + wd * rd * (1 - tax);
}

int main(){

double wd = .4;
double rd = .05;
double we = 1 - wd;
double re = capm(.02, 1.5, .08);
double tax = .4;

  printf("The WACC is %.2f\%\n", 100 * wacc(wd, we, rd, re, tax));
}

#+end_src

#+results:
: The WACC is 5.64%

* Internal and Sustainable Growth Rates

[[https://financial-education.github.io/growth_rates_and_EFN/][See here.]]  May help answer which firm is in the best financial position to expand.

* Case and Discussion Questions

**Which firm is in the best financial position to expand (buy assets) (win the routes to China)?**

Secondary: 

1. Have FedEx and UPS achieved their stated goals?
   + Fedex's goal: "superior financial returns".
   + UPS's goal: "long-term competitive return".
2. Can strong performance be expected in the future?
3. What has been the effect of the intense competition between the firms?
4. Which firm would you say is performing "better", and how might we define better?

* Other Notes

- pg 53 "the stock price of both companies had been rising steadily since those talks began..." this is a good example of the type of information you should know if you are going to speculate in the stock market.
- Fedex had a larger presence in China---was this noticeable in the stock prices?  100 new weekly cargo flights were to be divided between FedExand UPS.
- UPS stock was listed on the NYSE in 1999, used the stock to increase acquisitions (page 57).
- pg 59, Capex increases at an annual rate of 35% and 37% for UPS and Fedex respectively.  Also see exhibit 6 page 68.
- Air cargo market in China growing at 30% per year. Focus on export/import ($1 billion). Middle page 60.


* Relevant Lecture Notes

See [[https://financial-education.github.io/intro_corp_fin.html][lecture notes here]] on (at least) financial ratios and the cost of capital.


* Pecking Order Theory (Capital Structure)

Financing from cheapest to most expensive

1. Retained earnings (NOPAT)
2. Debt
3. Equity

So when you are thinking about which company is in a better position to expand its assets, you can think about these sources of financing.

1.  Which has greater NOPAT/EVA?
2.  Which has 'better' long-term debt ratios (higher TIE or lower D/E or EM)?
3.  How do we measure the ability to issue new equity?
   + New Equity decreases EPS and raises P/E.
   + Cost of equity? See this article: [[https://hbr.org/2012/07/do-you-know-your-cost-of-capital][https://hbr.org/2012/07/do-you-know-your-cost-of-capital]]

* Comparing stock performance

Using the provided stock prices:
- You can calculate annual returns and then use a t0test for significantly different mean returns.
- Calculate Sharpe Ratios.
